on:                    # Run the workflow for each of the following event:
  push:                # - A branch is pushed or updated.
    branches:
      - master
  pull_request:        # - A pull-request is openned or updated.
  workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.
  release:
    types: [created]   # - A release is created.

jobs:
  build-and-test:
    strategy:
      fail-fast: false # Don't stop all the workflows when one of them fails.
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          # List of build configurations to build & test
          - arch: generic
            simd: none
          - arch: x86_64
            simd: SSE2
          - arch: x86_64
            simd: AVX2

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Install and setup Alire package manager
      - uses: alire-project/setup-alire@v1
        with:
          version: 1.2.0

      # Install and setup Python
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Build the project using the validation build profile to enforce
      # static analysis and coding style.
      - name: Build ksum
        run: |
          alr build --validation -- \
            -XLIBKECCAK_ARCH=${{ matrix.arch }} \
            -XLIBKECCAK_SIMD=${{ matrix.simd }}
        # Don't assume the macOS runner is on x86-64
        if: ${{ matrix.os }} != 'macos-latest' || ${{ matrix.arch }} == generic

      # Run all tests
      - name: Run tests
        run: |
          cd tests
          python run_tests.py
